### PR TITLE
Add solaris support

### PR DESCRIPTION
**Pull request by gfrey**
Builds and simple examples worked.

### CODE REVIEW

**Comment by larzconwell** [comment]
You'll need to add the build flag to `ansi_unix.go` as well, and then this will be good.

**Comment by gfrey** [comment]
@larzconwell Thanks for catching that one!

**Comment by larzconwell** [comment]
Awesome! Thanks (:

**Comment by AttilaFueloep** [comment]
May I ask on which OS and go combination this worked for you? I'm seeing ```undefined: syscall.SYS_IOCTL``` errors on SmartOS. Please see #8 for details. It contains the  additional changes I needed, to make prompt compile on SmartOS.

**Comment by gfrey** [comment]
@AttilaFueloep I built it with go 1.6.3 on OpenIndiana Hipster.

**Comment by larzconwell** [comment]
@AttilaFueloep Good catch, that was a mistake on my part for not seeing that. @gfrey Could you look at #8 and try it out and verify that it works as you'd expect? I don't have a Solaris setup to test with, and I'd very appreciated!

**Comment by AttilaFueloep** [comment]
Oh, that explains everything. No worries and thanks for your good work!

**Pull request merged**
