### PR TITLE
Let prompt work on more BSDs

### PR DESCRIPTION
**Pull request by qbit**
Also modify the test so we use the local files vs having to use the lib in GOPATH. Not sure if this is the proper fix, or if I should be operating out of GOPATH (git clone github.com/bowery/prompt.git $GOPATH/blablabl style)

Let me know, and I will drop the change to the test file if needed.

### CODE REVIEW

**Comment by larzconwell** [comment]
Yeah if you could drop that test related change. Working on the code should be done inside GOPATH. That file also mostly just exists for the documentation side of things, though it would be really nice to get actual tests in the codebase.

Otherwise once that change gets removed it'll be good to go.

**Comment by NHOrus** [comment]
As I noted, added only FreeBSD because I was able to test it only on it. If this works on others - great.

**Comment by larzconwell** [comment]
It should be good as long as the terminals used on those systems support vt100 escape codes, which I'm pretty sure all unix systems do for the past whatever number of years. I looked into it a little and it the systems definitely support vt100 by default.

Other than that, the ioctl interfaces for termios all match across the systems looking more into it which isn't surprising, so this should be good.

**Comment by qbit** [comment]
Removed the change to the test file!

**Comment by larzconwell** [comment]
Great!

**Pull request merged**
